/** Single-record detail page, including real image digest and digital signature re-verification. */

import { escapeHtml } from "../lib/dom.js";
import {
  classificationLabel,
  classificationPill,
  coveragePct,
  formatGps,
  formatRecordDate,
  observationLabel,
  observationPill,
  signaturePill,
  syncPill
} from "../lib/format.js";
import { OBSERVATION_SOURCE_LEGACY } from "../lib/records.js";

/**
 * @param {object} record
 * @param {{checked:boolean, valid:boolean, reason:string}} integrity
 * @param {{valid:boolean, status:string, reason:string, keyId:string}} [signatureResult]
 */
export function recordDetail(record, integrity, signatureResult = null) {
  const legacy = record.observationSource === OBSERVATION_SOURCE_LEGACY;
  const guard = record.guard || {};
  const imageUrl = record.imageUrl;
  const isSigned = Boolean(record.signature);
  const sigStatus = signatureResult?.status || (isSigned ? "VERIFIED" : "UNSIGNED");

  const meta = [
    ["Test ID", record.id],
    ["Operator observation", observationLabel(record.observation)],
    ["Observation source", legacy ? "unclassified (schema v1)" : "field operator (authoritative)"],
    ["Presumptive classification", classificationLabel(record.classification)],
    ["Classification confidence", record.classificationConfidence ? `${record.classificationConfidence}% (algorithm confidence)` : "not assessed"],
    ["Observed at", record.observedAt ? formatRecordDate(record.observedAt) : "not recorded"],
    ["Observed by", record.observedBy || record.operator],
    ["Recorded at", formatRecordDate(record.date)],
    ["GPS", formatGps(record.lat, record.lng, record.accuracy)],
    ["Sample type", record.sampleType || "not recorded"],
    ["Frame quality", record.quality],
    ["Validation service", record.apiStatus],
    ["Cloud storage", record.sync === "synced" ? "uploaded to Firebase" : "on this device only"]
  ];

  const guardRows = [
    ["Reference swatch match", guard.accepted ? guard.colorName : "no match"],
    ["Coverage of frame", guard.accepted ? `${coveragePct(guard.coverage)}%` : "—"],
    ["Region aspect ratio", guard.accepted ? `${guard.aspect}:1` : "—"],
    ["Calibration status", record.calibrationStatus || "uncalibrated"],
    ["Guard verdict", guard.reason || "not evaluated"]
  ];

  return `
  <div class="page-head">
    <div><div class="eyebrow">AUDIT RECORD</div><h3>${escapeHtml(record.id)}</h3><p>What was captured, calibrated, and what the operator read from it.</p></div>
    <div style="display:flex;gap:8px;align-items:center">
      ${classificationPill(record.classification)}
      ${observationPill(record.observation)}
    </div>
  </div>

  ${legacy ? `<div class="disclaimer" style="margin-bottom:14px"><b>Migrated record.</b> This record was created before operator observations were stored, and its classification was never a verified reading. Treat the outcome as unknown.</div>` : ""}
  ${record.labReferralRequired ? `<div class="disclaimer warn" style="margin-bottom:14px"><b>Laboratory referral required.</b> A positive observation is presumptive. This record must be confirmed by laboratory analysis before it is relied upon.</div>` : ""}

  <div class="grid record">
    <div class="card">
      <div class="section-title"><h4>Record Details</h4><span>${escapeHtml(record.id)}</span></div>
      ${meta
        .map(
          ([label, value]) =>
            `<div class="meta-row"><span>${escapeHtml(label)}</span><span>${escapeHtml(String(value ?? "—"))}</span></div>`
        )
        .join("")}
      ${
        record.note
          ? `<div style="margin-top:16px"><small class="meta-label">OPERATOR NOTE</small><p class="note-body">${escapeHtml(record.note)}</p></div>`
          : ""
      }
    </div>

    <div class="card">
      <div class="section-title"><h4>Cryptographic Evidence</h4><span>TAMPER-EVIDENT</span></div>
      <div class="secure-box" style="margin-bottom:12px">
        <strong>${signatureResult?.valid ? "✓ Digital Signature VERIFIED" : sigStatus === "UNSIGNED" ? "— Not digitally signed (legacy record)" : "⚠ SIGNATURE INVALID (Tamper Detected)"}</strong>
        <p>${escapeHtml(signatureResult?.reason || (isSigned ? "Verified with operator public key" : "Legacy record without asymmetric signature"))}</p>
        <div class="hash" style="font-size:9px">${escapeHtml(record.signature ? `Sig: ${record.signature.slice(0, 32)}… (Key: ${record.signatureKeyId || "N/A"})` : "No signature")}</div>
        <small class="muted">Asymmetric ECDSA-P256-SHA256 signature generated by device key. Proves authenticity of canonical record fields.</small>
      </div>

      <div class="secure-box">
        <strong>${integrity?.checked ? (integrity.valid ? "✓ Frame Digest Re-verified" : "⚠ Frame Digest Mismatch") : "— Digest not re-verified"}</strong>
        <p>${escapeHtml(integrity?.reason || "no check performed")}</p>
        <div class="hash">${escapeHtml(record.hash || "no digest recorded")}</div>
        <small class="muted">SHA-256 computed over the captured image bytes. Proves the stored frame has not been altered.</small>
      </div>

      <div class="setting"><strong>Digital signature</strong>${signaturePill(sigStatus)}</div>
      <div class="setting"><strong>Signature algorithm</strong><span>${escapeHtml(record.signatureAlgorithm || "none")}</span></div>
      <div class="setting"><strong>Key Identifier</strong><span>${escapeHtml(record.signatureKeyId || "none")}</span></div>
      <div class="setting"><strong>Cloud storage</strong>${syncPill(record.sync)}</div>
    </div>

    <div class="card">
      <div class="section-title"><h4>Automated Colorimetric Classification</h4><span>PRESUMPTIVE</span></div>
      <div class="meta-row"><span>Classification</span><span>${classificationPill(record.classification)}</span></div>
      <div class="meta-row"><span>Algorithmic confidence</span><span>${record.classificationConfidence ? `${record.classificationConfidence}%` : "—"}</span></div>
      <div class="meta-row"><span>Classifier version</span><span>v${escapeHtml(record.classifierVersion || "1.0.0")}</span></div>
      <div class="meta-row"><span>Calibration version</span><span>v${escapeHtml(record.calibrationVersion || "1.0.0")}</span></div>
      ${
        record.normalizedReactionColor
          ? `<div class="meta-row"><span>Normalized reaction color</span><span><span style="display:inline-block;width:12px;height:12px;background:${escapeHtml(record.normalizedReactionColor)};border-radius:2px;vertical-align:middle;margin-right:4px"></span>${escapeHtml(record.normalizedReactionColor)}</span></div>`
          : ""
      }
      <p class="muted" style="margin-top:10px">Presumptive classification is derived from CIE Lab colorimetric analysis against reference reagent response profiles. It assists the operator but does NOT replace laboratory analysis.</p>
    </div>

    <div class="card">
      <div class="section-title"><h4>Reference Swatch &amp; Calibration</h4><span>MEASURED</span></div>
      ${guardRows
        .map(
          ([label, value]) =>
            `<div class="meta-row"><span>${escapeHtml(label)}</span><span>${escapeHtml(String(value))}</span></div>`
        )
        .join("")}
      <p class="muted">The reference card normalizes lighting variations (chromatic adaptation) across frames to improve colorimetric stability.</p>
    </div>
  </div>

  ${
    imageUrl
      ? `<div class="card" style="margin-top:14px">
          <div class="section-title"><h4>Captured frame</h4><span>${escapeHtml(record.id)}</span></div>
          <img class="record-image" src="${escapeHtml(imageUrl)}" alt="Captured frame for record ${escapeHtml(record.id)}" loading="lazy">
        </div>`
      : `<div class="card" style="margin-top:14px"><div class="section-title"><h4>Captured frame</h4><span>NOT STORED</span></div>
          <p class="muted">The frame is held in memory for this browser session only. It is not written to local storage, and it is only durable once the record has been uploaded — at which point <code>imageUrl</code> points at Firebase Storage.</p>
        </div>`
  }

  <div class="row-actions" style="margin-top:14px">
    <button class="btn btn-outline fc-3d" data-action="navigate" data-page="history">← Back</button>
    <button class="btn btn-blue fc-3d" data-action="export-record-pdf" data-id="${escapeHtml(record.id)}">Export PDF</button>
    <button class="btn btn-outline fc-3d" data-action="copy-verification" data-id="${escapeHtml(record.id)}">Copy verification details</button>
    ${record.signature ? `<button class="btn btn-outline fc-3d" data-action="demo-tamper" data-id="${escapeHtml(record.id)}">Demonstrate Tamper Detection</button>` : ""}
  </div>

  <div class="disclaimer" style="margin-top:14px"><b>Status of this record:</b> presumptive field-test result with cryptographic integrity verification. Laboratory confirmatory testing is required before reliance or legal action.</div>`;
}
